name: power-scraper-env
dependencies:
- anaconda
- python>=3.6

- ipywidgets
- pandas

- pip
- pip:
  - google-cloud-storage
  - openpyxl
  - python-dotenv
  - requests_cache
  - tqdm
  - -e git://github.com/consideRatio/entsoe-py.git#egg=entsoe
